// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://ubpixyvvpbwgdmyulwoz.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InVicGl4eXZ2cGJ3Z2RteXVsd296Iiwicm9sZSI6ImFub24iLCJpYXQiOjE3NzIxNDcxMDEsImV4cCI6MjA4NzcyMzEwMX0.OTj9QRphK0xU41fl0Lr5KyFJK7cXnudM8ZLzu6ugvRk";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});